/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: hxqyTBM9BHPEHcFjcH2YgS

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantsqUkztFogyl3I } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: qUkztFogyl3I/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantsqUkztFogyl3I
});
